title: "hellmakima"
description: "Infosec. Blog. Photography. Anything."
url: "https://hellmakima.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

minimal_mistakes_skin: "default"
color_scheme: light
accent_color: "#111111"

search: true
paginate: 5
paginate_path: /page:num/

author:
  name: "hellmakima"
  avatar: "/assets/images/avatar.png"
  bio: "Developer. Researcher. Builder."
  location: "Kolhapur, India"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hellmakima"